### Get the all registered accounts
GET {{baseUrl}}/admin/accounts

### Get all accounts that have "Bill" in their first name
GET {{baseUrl}}/admin/accounts?firstName=Bill

### Get all accounts that have "Mais" in their last name
GET {{baseUrl}}/admin/accounts?lastName=Mais

### Get all accounts that have the email "BillyMais@gmail.com"
GET {{baseUrl}}/admin/accounts?email=BillyMais@gmail.com

### Get the account with ID 1
GET {{baseUrl}}/admin/accounts/1

### Get the account with ID 1 and look at all the account's bids
GET {{baseUrl}}/admin/accounts/1/bids