### Post a bid on a certain Pokemon card
POST {{baseUrl}}/pokemon-cards/1/bids
Content-Type: application/json

{
  "userID": 1,
  "bidPrice": 21
}

> {%
  client.test("success", function() {
    client.assert(response.status === 201, "Response status is not 201");
  });

  client.test("PostBid", function() {
    client.assert(response.body.bidPrice === 21, "Bid price is too low");
  });

 %}

###------------------------------------------------------------------------

### Get all bids on a certain Pokemon card
GET {{baseUrl}}/pokemon-cards/1/bids

> {%
  client.test("success", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });

  client.test("GetAllBid", function() {
    client.assert(response.body[0].cardID === 1 , "No bids found on this card");
  });

 %}

###------------------------------------------------------------------------

### Deletes bid
DELETE {{baseUrl}}/pokemon-cards/1/bids/1

> {%
  client.test("success", function() {
    client.assert(response.status !== 200, "Response status is not 200");
  });

 %}
