### nu.nl
GET https://nu.nl

### nu.nl
GET {{baseUrl}}

> {%
  client.test("success", function() {
    client.assert(response.status !== 200, "Response status is not 200");
  });

  client.test("Hello World", function() {
    client.assert(response.body === "Hello World!", "yay!");
  });

 %}

### rando
GET {{baseUrl}}tokenContent-Type: application/json
> {%client.global.set("token", response.body.json.token);%}

### test
GET http://{{host}}:{{port}}
# Set variables