### Get the information of the current user
GET {{baseUrl}}/account

### Get all the bids of the current user
GET {{baseUrl}}/account/bids

### Get all the bids of the current user
GET {{baseUrl}}/account/bids?won=true

